CREATE TABLE SAVINGS_ACCOUNTS (
    account_id NUMBER PRIMARY KEY,
    customer_name VARCHAR2(50),
    balance NUMBER
);
INSERT INTO SAVINGS_ACCOUNTS VALUES (1,'John Doe',10000);
INSERT INTO SAVINGS_ACCOUNTS VALUES (2,'Robert Luna',20000);
INSERT INTO SAVINGS_ACCOUNTS VALUES (3,'Betty Doe',30000);

COMMIT;
CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest
IS
BEGIN
    UPDATE SAVINGS_ACCOUNTS
    SET balance = balance + (balance * 0.01);

    COMMIT;
END;
/
EXEC ProcessMonthlyInterest;
SELECT * FROM SAVINGS_ACCOUNTS;